inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'scratchpad.rb'

Style/Encoding:
  Enabled: true

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/Encoding:
  Enabled: false

AbcSize:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Style/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: false

Style/IndentHash:
  EnforcedStyle: consistent
  SupportedStyles:
    - special_inside_parentheses
    - consistent

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Enabled: true
